/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class FrmUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrmUtama
     */
    public FrmUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdKeluar = new javax.swing.JButton();
        labelJudul = new javax.swing.JLabel();
        cmdKategori = new javax.swing.JButton();
        cmdProduk = new javax.swing.JButton();
        cmdTransaksi = new javax.swing.JButton();
        cmdPegawai = new javax.swing.JButton();
        cmdPemesanan = new javax.swing.JButton();
        cmdLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdKeluar.setText("KELUAR");
        cmdKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKeluarMouseClicked(evt);
            }
        });
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJudul.setText("SISTEM INFORMASI PERCETAKAN SLOW");

        cmdKategori.setText("KATEGORI");
        cmdKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdKategoriMouseClicked(evt);
            }
        });
        cmdKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKategoriActionPerformed(evt);
            }
        });

        cmdProduk.setText("PRODUK");
        cmdProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProdukActionPerformed(evt);
            }
        });

        cmdTransaksi.setText("TRANSAKSI");
        cmdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTransaksiActionPerformed(evt);
            }
        });

        cmdPegawai.setText("PEGAWAI");
        cmdPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPegawaiMouseClicked(evt);
            }
        });
        cmdPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPegawaiActionPerformed(evt);
            }
        });

        cmdPemesanan.setText("PEMESANAN");
        cmdPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPemesananMouseClicked(evt);
            }
        });
        cmdPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPemesananActionPerformed(evt);
            }
        });

        cmdLaporan.setText("LAPORAN");
        cmdLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdLaporanMouseClicked(evt);
            }
        });
        cmdLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cmdKategori)
                                .addGap(30, 30, 30)
                                .addComponent(cmdTransaksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdPemesanan)
                                .addGap(40, 40, 40))
                            .addComponent(labelJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmdKeluar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cmdProduk)
                        .addGap(64, 64, 64)
                        .addComponent(cmdPegawai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdLaporan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdKategori)
                    .addComponent(cmdTransaksi)
                    .addComponent(cmdPemesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdProduk)
                    .addComponent(cmdPegawai)
                    .addComponent(cmdLaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdKeluar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKeluarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cmdKeluarMouseClicked

    private void cmdKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdKategoriMouseClicked
        new frmKategori().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdKategoriMouseClicked

    private void cmdProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProdukActionPerformed
        new FrmProduk().setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_cmdProdukActionPerformed

    private void cmdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTransaksiActionPerformed
        new FrmTransaksi().setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_cmdTransaksiActionPerformed

    private void cmdPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPegawaiMouseClicked
        // TODO add your handling code here:
        new FrmPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdPegawaiMouseClicked

    private void cmdPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPemesananMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdPemesananMouseClicked

    private void cmdPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPemesananActionPerformed
        // TODO add your handling code here:
        new FrmPemesanan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdPemesananActionPerformed

    private void cmdKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdKategoriActionPerformed

    private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
        // TODO add your handling code here:
            this.dispose();
         new FrmLogin().setVisible(true);
    }//GEN-LAST:event_cmdKeluarActionPerformed

    private void cmdLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdLaporanMouseClicked

    private void cmdPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdPegawaiActionPerformed

    private void cmdLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLaporanActionPerformed
        // TODO add your handling code here:
          new FrmLaporan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cmdLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdKategori;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdLaporan;
    private javax.swing.JButton cmdPegawai;
    private javax.swing.JButton cmdPemesanan;
    private javax.swing.JButton cmdProduk;
    private javax.swing.JButton cmdTransaksi;
    private javax.swing.JLabel labelJudul;
    // End of variables declaration//GEN-END:variables
}
